#!/usr/bin/env php
<?php 

use Benepfist\Xtrabackup\Manager\Console\TestCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Xtrabackup Manager', '0.0.1');
// Register all commands
$app->add(new TestCommand);

$app->run();