#!/usr/bin/env php
<?php 

use Benepfist\Xtrabackup\Manager\Console\IncrementalCommand;
use Benepfist\Xtrabackup\Manager\Console\BackupCommand;
use Benepfist\Xtrabackup\Manager\Console\ConfigureCommand;
use Benepfist\Xtrabackup\Manager\Console\RestoreCommand;
use Benepfist\Xtrabackup\Manager\Utils\FileHelper;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Xtrabackup Manager', '0.1.0');
// Register all commands
$app->add(new BackupCommand());
$app->add(new RestoreCommand());
$app->add(new IncrementalCommand(null, new FileHelper));
//$app->add(new ConfigureCommand());

$app->run();