#!/usr/bin/env php
<?php 

use Benepfist\Xtrabackup\Manager\Console\BackupCommand;
use Benepfist\Xtrabackup\Manager\Console\RestoreCommand;
use Benepfist\Xtrabackup\Manager\Console\ConfigureCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Xtrabackup Manager', '0.0.1');
// Register all commands
$app->add(new BackupCommand());
$app->add(new RestoreCommand());
//$app->add(new ConfigureCommand());

$app->run();